### ISSUE TITLE
Error When Compiling Into A Project

### ISSUE THREAD

**Issue by mergesort** [bdr99/node-mymazda#5]
Hey @bdr99, apologies for filing an issue if this isn't a problem with `node-mymazda` but I'll admit I'm relatively weak at Node and TypeScript and I *think* the issue is with the package.

I ran through the QuickStart code and was able to make API requests to my car, yay! But when I try to add `node-mymazda` into a project via npm and then run `npm run build` I run into this error.
```javascript
ERROR in ./node_modules/node-mymazda/dist/MyMazdaAPIConnection.js 38:25
Module parse failed: Unexpected token (38:25)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const logger = log4js_1.default.getLogger();
| function isSuccessfulEncryptedAPIResponse(responseBody) {
>     return (responseBody?.state === "S");
| }
| function isErrorEncryptedAPIResponse(responseBody) {
 @ ./node_modules/node-mymazda/dist/MyMazdaAPIController.js 6:47-80
 @ ./node_modules/node-mymazda/dist/MyMazdaAPIClient.js
 @ ./node_modules/node-mymazda/dist/index.js
 @ ./src/car-api.ts
 @ ./src/handler.ts
 @ ./src/index.ts
```
I tried to configure a webpack loader as the error message suggests, specifically the [TypeScript loader](https://webpack.js.org/guides/typescript/), but still run into the same error.

Any chance this is an issue with the library? And if not, is something you've seen before and happen to have insight into?

Thank you so much for the library, I'm really excited to integrate this into my personal app! 🙂

**Comment by bdr99** [comment]
Thanks for reaching out! I'm not sure whether or not this is a problem with the library, but let's try to find out.

The line of code pointed to by the error uses a feature called [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining), which is a relatively new JavaScript language feature and was added to Node.js in version 14. Are you using Node.js 14 or newer?

**Comment by mergesort** [comment]
Yep, I was on v14, and tried it with the latest LTS (v16.6.1), ending up with the same error in both cases.

**Comment by bdr99** [comment]
In order to resolve this, I think it would helpful if I could reproduce the issue. Is there a way you could share a minimal repo that reproduces the issue? Or perhaps the steps to create one?

**Comment by mergesort** [comment]
@bdr99 That's a good idea. I opened up the [repo](https://github.com/mergesort/mazda-api) I've been working in to provide a repro case. The most recent change I tried was updating webpack and a few other libraries to get it compiling, to no avail but with different errors. Undoing the most recent commit will provide the error I cited above.

**Comment by bdr99** [comment]
OK, I spent some time digging into this and I have a theory. I noticed that your project is based on `workers-typescript-template`, but it looks like it you started from an older version of the template, because I noticed the Webpack version in your package.json was 4.43.0 (before you manually updated it in https://github.com/mergesort/mazda-api/commit/826accf62fbdc18f9578199ba246b89006ec6892). Looking at the current version of [`workers-typescript-template`](https://github.com/cloudflare/worker-typescript-template), I can see from their package.json that it now uses Webpack 5.38.1 (looks like they upgraded from 4.43 to 5.38 in this commit from May 2021: https://github.com/cloudflare/worker-typescript-template/commit/62a19b3a661d771f6f8f276241b5703d3803078c). Also, according to [this comment](https://github.com/webpack/webpack/issues/10227#issuecomment-642734920), Webpack 5 is the first version to support optional chaining. I'm not sure how you started with such an old version of the template, but I think it would be worthwhile to try recreating your project from using the newest version of the template.

**Comment by mergesort** [comment]
You were right that the template was outdated, I was following [this guide](https://developers.cloudflare.com/pages/tutorials/build-an-api-with-workers/) from Cloudflare to build a small endpoint and it looks like they link to a different template. I restarted the project from the template you linked to since you're right, Webpack 5 does seem to support optional chaining.

Unfortunately though I end up with a whole set of different errors when I add `node-mymazda` (confirmed by building the project with and without the dependency) around log4js, cacheable-request, link.js, and more.

```javascript
WARNING in ./node_modules/log4js/lib/clustering.js 9:12-30
Module not found: Error: Can't resolve 'cluster' in '/Users/mergesort/Desktop/delivery-api/node_modules/log4js/lib'
 @ ./node_modules/log4js/lib/log4js.js 30:19-42
 @ ./node_modules/node-mymazda/dist/MyMazdaAPIConnection.js 7:33-50
 @ ./node_modules/node-mymazda/dist/MyMazdaAPIController.js 6:47-80
 @ ./node_modules/node-mymazda/dist/MyMazdaAPIClient.js 6:47-80
 @ ./node_modules/node-mymazda/dist/index.js 6:43-72
 @ ./src/car-api.ts 7:39-62
 @ ./src/handler.ts 24:25-45
 @ ./src/index.ts 3:18-38

3 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./node_modules/@szmarczak/http-timer/dist/source/index.js 4:15-30
Module not found: Error: Can't resolve 'util' in '/Users/mergesort/Desktop/delivery-api/node_modules/@szmarczak/http-timer/dist/source'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/got/dist/source/core/index.js 11:21-53
 @ ./node_modules/got/dist/source/create.js 17:15-32
 @ ./node_modules/got/dist/source/index.js 14:17-36 131:13-32
 @ ./node_modules/node-mymazda/dist/MyMazdaAPIConnection.js 6:30-44
 @ ./node_modules/node-mymazda/dist/MyMazdaAPIController.js 6:47-80
 @ ./node_modules/node-mymazda/dist/MyMazdaAPIClient.js 6:47-80
 @ ./node_modules/node-mymazda/dist/index.js 6:43-72
 @ ./src/car-api.ts 7:39-62
 @ ./src/handler.ts 24:25-45
 @ ./src/index.ts 3:18-38

ERROR in ./node_modules/cacheable-lookup/source/index.js 10:4-18
Module not found: Error: Can't resolve 'dns' in '/Users/mergesort/Desktop/delivery-api/node_modules/cacheable-lookup/source'
 @ ./node_modules/got/dist/source/core/index.js 12:27-54
 @ ./node_modules/got/dist/source/create.js 17:15-32
 @ ./node_modules/got/dist/source/index.js 14:17-36 131:13-32
 @ ./node_modules/node-mymazda/dist/MyMazdaAPIConnection.js 6:30-44
 @ ./node_modules/node-mymazda/dist/MyMazdaAPIController.js 6:47-80
 @ ./node_modules/node-mymazda/dist/MyMazdaAPIClient.js 6:47-80
 @ ./node_modules/node-mymazda/dist/index.js 6:43-72
 @ ./src/car-api.ts 7:39-62
 @ ./src/handler.ts 24:25-45
 @ ./src/index.ts 3:18-38
```

You can also see this seems to be caused by the library by commenting out `.get('/api/car/unlock', Car.unlockCarDoors)` as added in this [commit](https://github.com/mergesort/mazda-api/commit/50d2fca4853df5ced6970e4e7d4d7cff50706d1d) and watching the build succeed. 

I admit that I'm out of my depth here so any help is appreciated, but also please don't feel obligated because while I am genuinely appreciative of the help, I also understand that you're doing this in your free time and it seems like this is an issue with the dependencies and build tools, not specifically the library you've created.

**Comment by bdr99** [comment]
Hi @mergesort, I think I've gotten to the root of the problem. The main issue is that Cloudflare Workers don't run in a Node.js environment, so they can't use libraries that depend on Node.js modules such as `util`, `dns`, etc. `got` and `log4js`, which are both dependencies of `node-mymazda`, both depend on Node.js modules. This is why you are getting errors about those dependencies not being found. If you take a look at this page https://workers.cloudflare.com/works, under the heading "What packages don't work?", they explain that Cloudflare Workers run on the V8 JavaScript engine, which is the same one that Node.js uses, but it is still different from Node.js itself. It seems that only a small subset of npm packages can actually run directly on Cloudflare Workers.

Unfortunately, since `node-mymazda` was designed to run in Node.js and uses Node.js dependencies, I don't think it will be able to run on Cloudflare Workers. It might be possible to modify `node-mymazda` to run on Cloudflare Workers, but it would require replacing the two libraries `got` and `log4js` with ones that don't have any Node.js dependencies.

If you wouldn't mind sharing more details about what your end goal is, I might be able to suggest an alternative to Cloudflare Workers that would be more well suited for the task. Also, in case you're not aware, there is also a Python version of this library named [`pymazda`](https://github.com/bdr99/pymazda). It has the same feature set but might be easier to use if you're familiar with Python.

**Comment by mergesort** [comment]
Sorry about the delayed response, I much like seemingly everyone else in the world caught covid this week and wasn't feeling too well (but am ok now).

Thank you for doing that research, I didn't realize that Cloudflare had it's own custom runtime. I'd recently read [this article](https://techcrunch.com/2022/05/09/cloudflare-heads-effort-to-make-javascript-environments-interoperable/) and took it to mean that they were standardizing their runtime, but you're right and that explains why I'm running into these issues. I had two goals in mind, the first was that I wanted to learn more about Cloudflare and TypeScript for other personal projects so this seemed like a good fit for that, but I'd be happy with pretty much any serverless environment (since I'm looking to avoid maintenance) that supports JavaScript if you have suggestions. The goal related to `node-mymazda` is to create a few endpoints I could hit from a personal app to control my car.

I'm honestly less familiar with Python than I am with TypeScript and still would prefer to use your Node library if you do have good suggestions for a Node-friendly environment, but if not I can explore your other library and surely figure out how to get that up and running. 🙂

**Comment by bdr99** [comment]
Hi @mergesort sorry for the delay. I think [Heroku](https://www.heroku.com/) might be a good fit for what you're trying to do. I've worked with their platform a bit before and it worked well. It's platform as a service (PaaS), so they provide the infrastructure and take care of the maintenance like patching, etc. You just upload your codebase to them, and they run it. In that way it seems pretty similar to Cloudflare's offering. They have a good getting started guide for Node.js [here](https://devcenter.heroku.com/articles/getting-started-with-nodejs). They also have a free tier.

By the way, I'm not sure if you are aware, but node-mymazda can be used within JavaScript or TypeScript projects. Even though it's written in TypeScript, it works fine in a JavaScript project since the TS is compiled to JS. Since you're just getting started with Node.js, you might find it a bit easier working with vanilla JS instead of dealing with all of the additional tooling that comes with TS.

**Comment by mergesort** [comment]
Thanks a lot for the suggestions, I actually have decent experience with Heroku (and done a reasonable amount of server-work, it's actually the JS/TS tooling and ecosystem that's been tripping me up). I think the suggestion to use JavaScript is a good one, but I think I have a decent enough grasp on JS as a language and was looking explicitly looking to use this project to learn TypeScript more hands on, and unfortunately got tripped up on the part I find most confusing, the tooling/deployment (see: webpack) aspects. But I recognize it doesn't seem like there's a FaaS way to run this easily so I'll try a PaaS like Fly.io, Render (cause I've wanted to check those out), or even Heroku, and close out this issue because I recognize this discussion has swerved away pretty heavily from your project.

Thank you again for your help! 🙂
